// <auto-generated />
using MapApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MapApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20230926191645_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("MapApp.Models.Map", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("mapSvg")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Maps");
                });
#pragma warning restore 612, 618
        }
    }
}
